site_name: GeoSyilx Docs
nav:
  - Home: 'index.md'
  - 'Installing':
    - 'Under localhost': 'localhost.md'
    - 'Production Enhancements': 'production.md'
    - 'Developing': 'developing.md'
  - 'Managing':
    - 'Managing Permissions': 'managing_permissions.md'
    - 'Managing Groups': 'managing_groups.md'
    - 'Managing Users': 'managing_users.md'
  - 'Data Stewardship':
    - 'Managing Data': 'manage_data.md'
    - 'Uploading Data': 'uploading_data.md'
    - 'Completing Metadata': 'completing_metadata.md'
    - 'Creating Maps': 'creating_maps.md'
    - 'Creating Dashboards': 'creating_dashboards.md'
    - 'Creating GeoStories': 'creating_geostories.md'

theme:
  name: mkdocs
  user_color_mode_toggle: true
